### ISSUE TITLE
не могу собрать проект

### ISSUE THREAD

**Issue by ghB111** [10PAP/papfs#1]
Здравствуйте, коллеги! **_Очень сильно хочу очень сильно сжать свои данные._** Ваш проект не могу собрать. Вот мой код:
![image](https://user-images.githubusercontent.com/42515597/135812840-1fd634e2-a958-4361-9824-c314fed1611b.png)
Можете намекнуть, в чем проблема? Спасибо

**Comment by denisenes** [comment]
У вас пропущена скобка в 32 строке после 56 символа

**Comment by brocbyte** [comment]
![image](https://user-images.githubusercontent.com/52618858/135813925-373ab7bd-5b63-4e47-a0c4-c64125ef69c6.png)
Коллега, вот Ваше решение!

**Comment by ghB111** [comment]
Благодарю, коллеги!
